In [2]:
import sqlite3
import pandas as pd

db_path = "/home/zhgx/Portfolio_Adrian_Paneda/ecommerce-analytics-project/sql/ecommerce.db"
conn = sqlite3.connect(db_path)

print("Conected correctly to SQLite")

Conected correctly to SQLite

In [3]:
pd.read_sql("""
SELECT name 
FROM sqlite_master 
WHERE type='table';
""", conn)

         name
0  clean_data

In [4]:
pd.read_sql("PRAGMA table_info(clean_data);", conn)

   cid           name     type  notnull dflt_value  pk
0    0     event_time     TEXT        0       None   0
1    1     event_type     TEXT        0       None   0
2    2     product_id  INTEGER        0       None   0
3    3    category_id  INTEGER        0       None   0
4    4  category_code     TEXT        0       None   0
5    5          brand     TEXT        0       None   0
6    6          price     REAL        0       None   0
7    7        user_id  INTEGER        0       None   0
8    8   user_session     TEXT        0       None   0

In [5]:
pd.read_sql("SELECT COUNT(*) AS n_rows FROM clean_data;", conn)

   n_rows
0   99869

In [6]:
pd.read_sql("SELECT * FROM clean_data LIMIT 5;", conn)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-02 02:49:24+00:00,view,1500208,2053013552955916539,computers.peripherals.printer,xerox,94.98,517567639,69e6455e-60ba-45aa-8adf-e2f8368b38e2
1,2019-10-03 09:22:26+00:00,view,26402505,2053013563651392361,unknown,unknown,950.73,515486711,530fd038-f953-4642-ae76-899927504bcc
2,2019-10-02 18:06:36+00:00,view,3801361,2053013566176363511,appliances.iron,tefal,84.69,512990124,7383f94e-d0a2-48d8-9ced-f73c4b16db45
3,2019-10-03 16:12:48+00:00,view,11600016,2053013554566529381,computers.desktop,microlab,179.12,518802500,f18c0549-4e6b-4058-a75f-50ef19ea9340
4,2019-10-01 06:38:24+00:00,view,17400231,2053013558727279193,unknown,unknown,3.09,519078297,aeceaca3-8b2b-4540-9a34-98cc9ff37f4e

In [7]:
pd.read_sql("SELECT * FROM clean_data WHERE price > 100 LIMIT 5;", conn)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-03 09:22:26+00:00,view,26402505,2053013563651392361,unknown,unknown,950.73,515486711,530fd038-f953-4642-ae76-899927504bcc
1,2019-10-03 16:12:48+00:00,view,11600016,2053013554566529381,computers.desktop,microlab,179.12,518802500,f18c0549-4e6b-4058-a75f-50ef19ea9340
2,2019-10-02 14:42:59+00:00,view,1005105,2053013555631882655,electronics.smartphone,apple,1415.48,513463617,834262d7-9b4d-4726-83f5-e1014a0e8fed
3,2019-10-02 15:21:53+00:00,view,1005179,2053013555631882655,electronics.smartphone,unknown,900.64,513911405,e9724429-c4fa-4610-8cc7-e0346500c405
4,2019-10-03 16:54:45+00:00,view,31501032,2053013558031024687,unknown,luminarc,158.56,542401976,165ee42e-bd88-4d7e-92a3-c2b33a5967e5