In [1]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("postgresql+psycopg2://postgres:74627620adri@localhost:5432/postgres")

In [2]:
orders = pd.read_sql("SELECT * FROM orders", engine)
deliveries = pd.read_sql("SELECT * FROM deliveries", engine)
restaurants = pd.read_sql("SELECT * FROM restaurants", engine)
riders = pd.read_sql("SELECT * FROM riders", engine)
order_events = pd.read_sql("SELECT * FROM order_events", engine)

In [5]:
orders.head()

,order_id,created_at,order_value,items_count,estimated_prep_time,estimated_delivery_time,customer_lat,customer_lon,order_status,restaurant_id,weather_level,traffic_level
0,1,2026-01-17 12:31:24,80.13,6,17,21,43.275816,-2.914033,DELIVERED,39,RAIN,MEDIUM
1,2,2026-01-05 12:24:54,60.95,6,20,22,43.274594,-2.953613,DELIVERED,26,CLEAR,MEDIUM
2,3,2026-01-09 23:42:54,60.08,4,22,16,43.229625,-2.950303,DELIVERED,48,CLEAR,MEDIUM
3,4,2026-01-24 19:54:54,70.73,5,14,14,43.247773,-2.899567,DELIVERED,1,CLEAR,LOW
4,5,2026-01-31 13:21:26,34.68,2,24,37,43.279074,-2.965174,DELIVERED,10,RAIN,HIGH

In [6]:
deliveries.head()

,delivery_id,order_id,rider_id,assigned_at,picked_up_at,delivered_at,hour,day,month,prep_minutes,delivery_minutes,total_minutes
0,1,1,3,2026-01-17 12:35:24,2026-01-17 13:02:24,2026-01-17 13:23:24,12,Saturday,1,27.0,21.0,48.0
1,2,2,33,2026-01-05 12:28:54,2026-01-05 12:54:54,2026-01-05 13:16:54,12,Monday,1,26.0,22.0,48.0
2,3,3,69,2026-01-09 23:45:54,2026-01-10 00:15:54,2026-01-10 00:31:54,23,Friday,1,30.0,16.0,46.0
3,4,4,74,2026-01-24 19:58:54,2026-01-24 20:16:54,2026-01-24 20:30:54,19,Saturday,1,18.0,14.0,32.0
4,5,5,39,2026-01-31 13:25:26,2026-01-31 13:56:26,2026-01-31 14:33:26,13,Saturday,1,31.0,37.0,68.0

In [7]:
restaurants.head()

,restaurant_id,restaurant_name,cuisine_category,base_prep_time,capacity,restaurant_zone,restaurant_lat,restaurant_lon
0,1,ASIAN_PLACE_1,ASIAN,16,10,SOUTH,43.224489,-2.974651
1,2,ITALIAN_PLACE_2,ITALIAN,25,33,WEST,43.208694,-2.943589
2,3,ITALIAN_PLACE_3,ITALIAN,16,16,NORTH,43.250536,-2.987081
3,4,BURGER_PLACE_4,BURGER,18,23,NORTH,43.244921,-2.959399
4,5,ITALIAN_PLACE_5,ITALIAN,17,32,EAST,43.234025,-2.972897

In [8]:
riders.head()

   rider_id rider_name home_zone vehicle_type  max_orders_per_hour
0         1    RIDER_1      WEST         BIKE                    2
1         2    RIDER_2      WEST         BIKE                    5
2         3    RIDER_3      WEST    MOTORBIKE                    4
3         4    RIDER_4     NORTH    MOTORBIKE                    3
4         5    RIDER_5     SOUTH    MOTORBIKE                    3

In [9]:
order_events.head()

   event_id  order_id event_name     event_timestamp
0         1         1    CREATED 2026-01-17 12:31:24
1         2         1   ACCEPTED 2026-01-17 12:35:24
2         3         1  PREPARING 2026-01-17 12:37:24
3         4         1      READY 2026-01-17 12:54:24
4         5         1  PICKED_UP 2026-01-17 13:02:24